#! /bin/sh

sxhkd &
setxkbmap gb -option caps:ctrl_modifier&
xcape -e "Caps_Lock=Escape"&
dropbox&
xset -dpms&
autocutsel&
autocutsel -s PRIMARY&
xsetroot -cursor_name left_ptr



bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Leave a gap for polybar

# Focus follows mouse
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc monitor -d I II III IV V VI VII VIII IX X
sleep 0.5 && feh --bg-fill --randomize /home/olie/Pictures/Wallpapers/earth/&
sleep 0.5 && polybar examplebsp
