#! /bin/sh

# xrandr --output DP-0 --auto --primary
# xrandr --output HDMI-1 --auto --left-of DP-0 --rotate left
xrandr --output HDMI-1 --auto --primary --rotate normal
xrandr --output DP-0 --auto --right-of HDMI-1 --rotate left
$HOME/bin/fix_internet.sh

SXHKD_SHELL=/bin/sh sxhkd &
dropbox&
xset -dpms
xset s off
# autocutsel&
# autocutsel -s PRIMARY&



bspc config border_width         1
bspc config window_gap           20

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Leave a gap for polybar

# Focus follows mouse
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# This causes issues with Steam : (
bspc config pointer_follows_focus false

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off


sleep 0.5 && feh --bg-fill --randomize /home/olie/Pictures/Earthpapers/&
# Single monitor setup
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10

# or Multimonitor setup
bspc monitor DP-0 -d 2 4 6 8 10
bspc monitor HDMI-1 -d 1 3 5 7 9

env MONITOR=DP-0 polybar hidpi&
env MONITOR=HDMI-1 polybar hidpi&
# dunst& # omg ultra annoying notification thing ... it was here all along!?
