#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

# Undo files for vim
mkdir -p .undodir


echo "Install programmes"
if [ -z "$DISPLAY" ]; then
    toguiornotgui="vim";
else
    toguiornotgui="gvim firefox gnome-terminal";
fi
fonts="noto-fonts ttf-iosevka-term"
web="elinks surfraw dnsutils wget curl openssh npm"
terminal="tmux screen tldr fish fzf keychain neovim"
code="python python-pip python2 python2-pip julia git python-neovim"
sudo pacman --needed -Sy pacaur
pacaur --needed -Sy $fonts $web $terminal $code $toguiornotgui
read
echo "Update vim plugins"
vim +PlugInstall +PlugUpdate +PlugUpgrade +qall

echo "Update fish plugins"
fish -c fisher up 

# Fish abbreviations
fish -c "abbr g git
abbr gs 'git status'
abbr ga 'git add'
abbr gp 'git pull'
abbr gcm 'git checkout master'
abbr gc 'git checkout'
abbr grc 'git rebase --continue'
abbr nrb 'npm run build'
abbr ts 'task sync'
abbr t 'task'
abbr ta 'tmux attach; or tmux'"
